language: node_js
cache: npm
stages:
  - check
  - test
  - cov

node_js:
  - '10'

os:
  - linux
  - osx
  - windows
before_install:
  - choco install sysinternals -Y
  - Listdlls64.exe -d KERNEL32.dll
  - Listdlls64.exe -d SHLWAPI.dll
  - Listdlls64.exe -d msdmo.dll
  - Listdlls64.exe -d Secur32.dll
  - Listdlls64.exe -d WINMM.dll
  - Listdlls64.exe -d WS2_32.dll
  - Listdlls64.exe -d IPHLPAPI.DLL
  - Listdlls64.exe -d USER32.dll
  - Listdlls64.exe -d ADVAPI32.dll
  - Listdlls64.exe -d ole32.dll
script: npx nyc -s npm run test:node -- --bail
after_success: npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov

jobs:
  include:
    - stage: check
      script:
        - npx aegir commitlint --travis
        - npx aegir dep-check -- -i wrtc -i electron-webrtc
        - npm run lint

    - stage: test
      name: chrome
      addons:
        chrome: stable
      script:
        - npx aegir test -t browser
        - npx aegir test -t webworker

    - stage: test
      name: firefox
      addons:
        firefox: latest
      script:
        - npx aegir test -t browser -- --browsers FirefoxHeadless
        - npx aegir test -t webworker -- --browsers FirefoxHeadless

notifications:
  email: false